In [8]:
import psycopg2
import pandas as pd

In [3]:
host = 'hh-pgsql-public.ebi.ac.uk'
port = 5432
database = 'pfmegrnargs'
user = 'reader'
password = 'NWDMCE5xdipIjRrp'

In [4]:
try:
    conn = psycopg2.connect(dbname=database, user=user, password=password, host=host)
except:
    print('Can`t establish connection to database')

In [5]:
with conn.cursor() as cursor:
    cursor.execute('SELECT * FROM rnc_database limit 10')
    rnc_10 = cursor.fetchall()

In [6]:
rnc_10[:2]

[(1,
  datetime.datetime(2017, 5, 1, 0, 0),
  'RNACEN',
  'ENA',
  884,
  'ENA',
  'Y',
  ' ',
  'ENA',
  '',
  412,
  10,
  900074,
  12086180,
  814855,
  "provides a comprehensive record of the world's nucleotide sequencing information",
  'https://www.ebi.ac.uk/ena/browser/',
  [{'upi': 'URS00002D0E0C', 'taxid': 10090},
   {'upi': 'URS000035EE7E', 'taxid': 9606},
   {'upi': 'URS0000000001', 'taxid': 77133}],
  [{'title': 'The European Nucleotide Archive in 2017',
    'authors': 'Silvester et al.',
    'journal': 'Nucleic Acids Res. 2017',
    'pubmed_id': '29140475'}]),
 (5,
  datetime.datetime(2017, 5, 17, 0, 0),
  'RNACEN',
  'VEGA',
  98,
  'VEGA',
  'N',
  ' ',
  'VEGA',
  'PRJEB4568',
  None,
  None,
  None,
  0,
  0,
  'is a repository for high-quality gene models produced by the manual annotation of vertebrate genomes. Human and mouse data from Vega are merged into <a href="http://www.gencodegenes.org/" target="_blank">GENCODE</a>',
  'http://vega.sanger.ac.uk/',
  [{'upi': 'URS00000B15DA', 'taxid': 9606},
   {'upi': 'URS00000A54A6', 'taxid': 9606},
   {'upi': 'URS0000301B08', 'taxid': 9606}],
  [{'title': 'The GENCODE v7 catalog of human long noncoding RNAs: analysis of their gene structure, evolution, and expression.',
    'authors': 'Derrien T., Johnson R., Bussotti G., Tanzer A., Djebali S., Tilgner H., Guernec G., Martin D., Merkel A., Knowles DG. et al.',
    'journal': 'Genome Res. 22(9): 1775-1789 (2012 Sep)',
    'pubmed_id': '22955988'},
   {'title': 'GENCODE: the reference human genome annotation for The ENCODE Project',
    'authors': 'Harrow J., Frankish A., Gonzalez JM., Tapanari E., Diekhans M., Kokocinski F., Aken BL., Barrell D., Zadissa A., Searle S. et al.',
    'journal': 'Genome Res. 22(9): 1760-1774 (2012 Sep)',
    'pubmed_id': '22955987'}])]

In [9]:
rnc_df = pd.DataFrame(rnc_10)
rnc_df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,1,2017-05-01 00:00:00.000000,RNACEN,ENA,884,ENA,Y,,ENA,,412.0,10.0,900074.0,12086180,814855,provides a comprehensive record of the world's...,https://www.ebi.ac.uk/ena/browser/,"[{'upi': 'URS00002D0E0C', 'taxid': 10090}, {'u...",[{'title': 'The European Nucleotide Archive in...
1,5,2017-05-17 00:00:00.000000,RNACEN,VEGA,98,VEGA,N,,VEGA,PRJEB4568,NaN,NaN,NaN,0,0,is a repository for high-quality gene models p...,http://vega.sanger.ac.uk/,"[{'upi': 'URS00000B15DA', 'taxid': 9606}, {'up...",[{'title': 'The GENCODE v7 catalog of human lo...
2,26,2017-05-01 00:00:00.000000,RNACEN,GENCODE,450,GENCODE,N,,GENCODE,,889.0,32.0,205012.0,47677,2,produces high quality reference gene annotatio...,http://gencodegenes.org/,"[{'upi': 'URS00000B15DA', 'taxid': 9606}, {'up...",[{'title': 'GENCODE: the reference human genom...
3,55,2023-10-10 15:02:45.191606,RNACEN,MGNIFY,839,MGnify,Y,None,MGnify,None,151.0,27.0,3514.0,135924,1929,None,None,None,None
4,41,2017-05-01 00:00:00.000000,RNACEN,GENECARDS,867,MalaCards,Y,,GeneCards,,1298.0,16.0,347561.0,517673,1,"is a searchable, integrative database that pro...",https://www.genecards.org/,"[{'upi': 'URS0000EBFCE3', 'taxid': 9606}, {'up...",[{'title': 'The GeneCards Suite: From Gene Dat...

In [11]:
with conn.cursor() as cursor:
    cursor.execute('SELECT display_name, num_sequences, num_organisms, url FROM rnc_database limit 10')
    selected_rnc_10 = cursor.fetchall()
#selected_rnc_10[:2]

[('ENA', 12086180, 814855, 'https://www.ebi.ac.uk/ena/browser/'),
 ('VEGA', 0, 0, 'http://vega.sanger.ac.uk/')]

In [12]:
selected_rnc_df = pd.DataFrame(selected_rnc_10)
selected_rnc_df.head
#названия столбцов не подписываются автоматически

           0         1       2                                   3
0        ENA  12086180  814855  https://www.ebi.ac.uk/ena/browser/
1       VEGA         0       0           http://vega.sanger.ac.uk/
2    GENCODE     47677       2            http://gencodegenes.org/
3     MGnify    135924    1929                                None
4  GeneCards    517673       1          https://www.genecards.org/