In [51]:
import polars as pl
import pandas as pd
import bottleneck as bn
import numpy as np

In [ ]:
#считайте датасет с помощью polars

In [5]:
df_pl = pl.read_csv("train.csv")
df_pl

shape: (891, 12)
┌─────────────┬──────────┬────────┬────────────────────────────────┬───┬──────────────────┬─────────┬───────┬──────────┐
│ PassengerId ┆ Survived ┆ Pclass ┆ Name                           ┆ … ┆ Ticket           ┆ Fare    ┆ Cabin ┆ Embarked │
│ ---         ┆ ---      ┆ ---    ┆ ---                            ┆   ┆ ---              ┆ ---     ┆ ---   ┆ ---      │
│ i64         ┆ i64      ┆ i64    ┆ str                            ┆   ┆ str              ┆ f64     ┆ str   ┆ str      │
╞═════════════╪══════════╪════════╪════════════════════════════════╪═══╪══════════════════╪═════════╪═══════╪══════════╡
│ 1           ┆ 0        ┆ 3      ┆ Braund, Mr. Owen Harris        ┆ … ┆ A/5 21171        ┆ 7.25    ┆ null  ┆ S        │
│ 2           ┆ 1        ┆ 1      ┆ Cumings, Mrs. John Bradley     ┆ … ┆ PC 17599         ┆ 71.2833 ┆ C85   ┆ C        │
│             ┆          ┆        ┆ (Fl…                           ┆   ┆                  ┆         ┆       ┆          │
│ 3           ┆ 1        ┆ 3      ┆ Heikkinen, Miss. Laina         ┆ … ┆ STON/O2. 3101282 ┆ 7.925   ┆ null  ┆ S        │
│ 4           ┆ 1        ┆ 1      ┆ Futrelle, Mrs. Jacques Heath   ┆ … ┆ 113803           ┆ 53.1    ┆ C123  ┆ S        │
│             ┆          ┆        ┆ (…                             ┆   ┆                  ┆         ┆       ┆          │
│ 5           ┆ 0        ┆ 3      ┆ Allen, Mr. William Henry       ┆ … ┆ 373450           ┆ 8.05    ┆ null  ┆ S        │
│ …           ┆ …        ┆ …      ┆ …                              ┆ … ┆ …                ┆ …       ┆ …     ┆ …        │
│ 887         ┆ 0        ┆ 2      ┆ Montvila, Rev. Juozas          ┆ … ┆ 211536           ┆ 13.0    ┆ null  ┆ S        │
│ 888         ┆ 1        ┆ 1      ┆ Graham, Miss. Margaret Edith   ┆ … ┆ 112053           ┆ 30.0    ┆ B42   ┆ S        │
│ 889         ┆ 0        ┆ 3      ┆ Johnston, Miss. Catherine      ┆ … ┆ W./C. 6607       ┆ 23.45   ┆ null  ┆ S        │
│             ┆          ┆        ┆ Hele…                          ┆   ┆                  ┆         ┆       ┆          │
│ 890         ┆ 1        ┆ 1      ┆ Behr, Mr. Karl Howell          ┆ … ┆ 111369           ┆ 30.0    ┆ C148  ┆ C        │
│ 891         ┆ 0        ┆ 3      ┆ Dooley, Mr. Patrick            ┆ … ┆ 370376           ┆ 7.75    ┆ null  ┆ Q        │
└─────────────┴──────────┴────────┴────────────────────────────────┴───┴──────────────────┴─────────┴───────┴──────────┘

In [ ]:
#выведите основную информацию о датасете

In [6]:
df_pl.describe()

shape: (9, 13)
┌────────────┬─────────────┬──────────┬──────────┬───┬───────────┬───────────┬───────┬──────────┐
│ statistic  ┆ PassengerId ┆ Survived ┆ Pclass   ┆ … ┆ Ticket    ┆ Fare      ┆ Cabin ┆ Embarked │
│ ---        ┆ ---         ┆ ---      ┆ ---      ┆   ┆ ---       ┆ ---       ┆ ---   ┆ ---      │
│ str        ┆ f64         ┆ f64      ┆ f64      ┆   ┆ str       ┆ f64       ┆ str   ┆ str      │
╞════════════╪═════════════╪══════════╪══════════╪═══╪═══════════╪═══════════╪═══════╪══════════╡
│ count      ┆ 891.0       ┆ 891.0    ┆ 891.0    ┆ … ┆ 891       ┆ 891.0     ┆ 204   ┆ 889      │
│ null_count ┆ 0.0         ┆ 0.0      ┆ 0.0      ┆ … ┆ 0         ┆ 0.0       ┆ 687   ┆ 2        │
│ mean       ┆ 446.0       ┆ 0.383838 ┆ 2.308642 ┆ … ┆ null      ┆ 32.204208 ┆ null  ┆ null     │
│ std        ┆ 257.353842  ┆ 0.486592 ┆ 0.836071 ┆ … ┆ null      ┆ 49.693429 ┆ null  ┆ null     │
│ min        ┆ 1.0         ┆ 0.0      ┆ 1.0      ┆ … ┆ 110152    ┆ 0.0       ┆ A10   ┆ C        │
│ 25%        ┆ 224.0       ┆ 0.0      ┆ 2.0      ┆ … ┆ null      ┆ 7.925     ┆ null  ┆ null     │
│ 50%        ┆ 446.0       ┆ 0.0      ┆ 3.0      ┆ … ┆ null      ┆ 14.4542   ┆ null  ┆ null     │
│ 75%        ┆ 669.0       ┆ 1.0      ┆ 3.0      ┆ … ┆ null      ┆ 31.0      ┆ null  ┆ null     │
│ max        ┆ 891.0       ┆ 1.0      ┆ 3.0      ┆ … ┆ WE/P 5735 ┆ 512.3292  ┆ T     ┆ S        │
└────────────┴─────────────┴──────────┴──────────┴───┴───────────┴───────────┴───────┴──────────┘

In [11]:
df_pl.dtypes

[Int64,
 Int64,
 Int64,
 String,
 String,
 Float64,
 Int64,
 Int64,
 String,
 Float64,
 String,
 String]

In [7]:
df_pl.null_count()

shape: (1, 12)
┌─────────────┬──────────┬────────┬──────┬───┬────────┬──────┬───────┬──────────┐
│ PassengerId ┆ Survived ┆ Pclass ┆ Name ┆ … ┆ Ticket ┆ Fare ┆ Cabin ┆ Embarked │
│ ---         ┆ ---      ┆ ---    ┆ ---  ┆   ┆ ---    ┆ ---  ┆ ---   ┆ ---      │
│ u32         ┆ u32      ┆ u32    ┆ u32  ┆   ┆ u32    ┆ u32  ┆ u32   ┆ u32      │
╞═════════════╪══════════╪════════╪══════╪═══╪════════╪══════╪═══════╪══════════╡
│ 0           ┆ 0        ┆ 0      ┆ 0    ┆ … ┆ 0      ┆ 0    ┆ 687   ┆ 2        │
└─────────────┴──────────┴────────┴──────┴───┴────────┴──────┴───────┴──────────┘

In [8]:
df_pl.mean()

shape: (1, 12)
┌─────────────┬──────────┬──────────┬──────┬───┬────────┬───────────┬───────┬──────────┐
│ PassengerId ┆ Survived ┆ Pclass   ┆ Name ┆ … ┆ Ticket ┆ Fare      ┆ Cabin ┆ Embarked │
│ ---         ┆ ---      ┆ ---      ┆ ---  ┆   ┆ ---    ┆ ---       ┆ ---   ┆ ---      │
│ f64         ┆ f64      ┆ f64      ┆ str  ┆   ┆ str    ┆ f64       ┆ str   ┆ str      │
╞═════════════╪══════════╪══════════╪══════╪═══╪════════╪═══════════╪═══════╪══════════╡
│ 446.0       ┆ 0.383838 ┆ 2.308642 ┆ null ┆ … ┆ null   ┆ 32.204208 ┆ null  ┆ null     │
└─────────────┴──────────┴──────────┴──────┴───┴────────┴───────────┴───────┴──────────┘

In [ ]:
#посчитайте количество пассажиров каждого класса

In [14]:
df_pl.get_column("Pclass").value_counts()

shape: (3, 2)
┌────────┬───────┐
│ Pclass ┆ count │
│ ---    ┆ ---   │
│ i64    ┆ u32   │
╞════════╪═══════╡
│ 2      ┆ 184   │
│ 1      ┆ 216   │
│ 3      ┆ 491   │
└────────┴───────┘

In [ ]:
#выведите количество выживших мужчин и женщин на корабле

In [21]:
df_pl.group_by("Sex").agg((pl.col("Survived")==1).sum())

shape: (2, 2)
┌────────┬──────────┐
│ Sex    ┆ Survived │
│ ---    ┆ ---      │
│ str    ┆ u32      │
╞════════╪══════════╡
│ male   ┆ 109      │
│ female ┆ 233      │
└────────┴──────────┘

In [ ]:
#выведите часть таблицы с пассажирами, возраст которых больше 44 лет

In [22]:
df_pl.filter(pl.col("Age")>44)

shape: (115, 12)
┌─────────────┬──────────┬────────┬─────────────────────────────────┬───┬────────────┬─────────┬───────┬──────────┐
│ PassengerId ┆ Survived ┆ Pclass ┆ Name                            ┆ … ┆ Ticket     ┆ Fare    ┆ Cabin ┆ Embarked │
│ ---         ┆ ---      ┆ ---    ┆ ---                             ┆   ┆ ---        ┆ ---     ┆ ---   ┆ ---      │
│ i64         ┆ i64      ┆ i64    ┆ str                             ┆   ┆ str        ┆ f64     ┆ str   ┆ str      │
╞═════════════╪══════════╪════════╪═════════════════════════════════╪═══╪════════════╪═════════╪═══════╪══════════╡
│ 7           ┆ 0        ┆ 1      ┆ McCarthy, Mr. Timothy J         ┆ … ┆ 17463      ┆ 51.8625 ┆ E46   ┆ S        │
│ 12          ┆ 1        ┆ 1      ┆ Bonnell, Miss. Elizabeth        ┆ … ┆ 113783     ┆ 26.55   ┆ C103  ┆ S        │
│ 16          ┆ 1        ┆ 2      ┆ Hewlett, Mrs. (Mary D Kingcome… ┆ … ┆ 248706     ┆ 16.0    ┆ null  ┆ S        │
│ 34          ┆ 0        ┆ 2      ┆ Wheadon, Mr. Edward H           ┆ … ┆ C.A. 24579 ┆ 10.5    ┆ null  ┆ S        │
│ 53          ┆ 1        ┆ 1      ┆ Harper, Mrs. Henry Sleeper (My… ┆ … ┆ PC 17572   ┆ 76.7292 ┆ D33   ┆ C        │
│ …           ┆ …        ┆ …      ┆ …                               ┆ … ┆ …          ┆ …       ┆ …     ┆ …        │
│ 858         ┆ 1        ┆ 1      ┆ Daly, Mr. Peter Denis           ┆ … ┆ 113055     ┆ 26.55   ┆ E17   ┆ S        │
│ 863         ┆ 1        ┆ 1      ┆ Swift, Mrs. Frederick Joel (Ma… ┆ … ┆ 17466      ┆ 25.9292 ┆ D17   ┆ S        │
│ 872         ┆ 1        ┆ 1      ┆ Beckwith, Mrs. Richard Leonard… ┆ … ┆ 11751      ┆ 52.5542 ┆ D35   ┆ S        │
│ 874         ┆ 0        ┆ 3      ┆ Vander Cruyssen, Mr. Victor     ┆ … ┆ 345765     ┆ 9.0     ┆ null  ┆ S        │
│ 880         ┆ 1        ┆ 1      ┆ Potter, Mrs. Thomas Jr (Lily A… ┆ … ┆ 11767      ┆ 83.1583 ┆ C50   ┆ C        │
└─────────────┴──────────┴────────┴─────────────────────────────────┴───┴────────────┴─────────┴───────┴──────────┘

In [ ]:
#считайте датасет с помощью pandas

In [25]:
df_pd = pd.read_csv("train.csv")
df_pd

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
#посчитайте средний возраст пассажиров и его стандартное отклонение с помощью bottleneck

In [ ]:
#средний возраст пассажиров

In [29]:
bn.nanmean(df_pd["Age"])

29.69911764705882

In [ ]:
#стандартное отклонение

In [30]:
bn.nanstd(df_pd["Age"])

14.516321150817317

In [ ]:
#для каждого пассажира умножьте значение столбца Fare на 1.3 и сохраните результаты как новый столбец Fare_new

In [45]:
df_pd["Fare_new"]= df_pd["Fare"].apply(lambda row: row * 1.3)
df_pd["Fare_new"]

0       9.42500
1      92.66829
2      10.30250
3      69.03000
4      10.46500
         ...
886    16.90000
887    39.00000
888    30.48500
889    39.00000
890    10.07500
Name: Fare_new, Length: 891, dtype: float64

In [ ]:
#считайте датасет из файла housing.csv с помощью pandas

In [48]:
df = pd.read_csv("Housing.csv")
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [ ]:
#для каждого столбца определите оптимальный тип данных, напишите выводы

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB

In [54]:
df["price"].max()

13300000

In [ ]:
 #   Column            Dtype       оптимальный тип
---  ------            --------------  ----- 
 #   price                 int64      int32
 #   area                  int64      int16
 #   bedrooms              int64      int8
 #   bathrooms             int64      int8
 #   stories               int64      int8
 #   mainroad              object     category
 #   guestroom             object     category
 #   basement              object     category
 #   hotwaterheating       object     category
 #  airconditioning       object      category
 #  parking               int64       int8
 #  prefarea              object      category
 #  furnishingstatus      object      category

In [ ]:
#поменяйтие типы данных и сравните потребление памяти

In [55]:
df['price'] = df['price'].astype(np.int32)
df['area'] = df['area'].astype(np.int16)
df['bedrooms'] = df['bedrooms'].astype(np.int8)
df['bathrooms'] = df['bathrooms'].astype(np.int8)
df['stories'] = df['stories'].astype(np.int8)
df['parking'] = df['parking'].astype(np.int8)

In [59]:
df['mainroad'] = df['mainroad'].astype("category")
df['guestroom'] = df['guestroom'].astype("category")
df['basement'] = df['basement'].astype("category")
df['hotwaterheating'] = df['hotwaterheating'].astype("category")
df['airconditioning'] = df['airconditioning'].astype("category")
df['prefarea'] = df['prefarea'].astype("category")
df['furnishingstatus'] = df['furnishingstatus'].astype("category")

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int32
 1   area              545 non-null    int16
 2   bedrooms          545 non-null    int8
 3   bathrooms         545 non-null    int8
 4   stories           545 non-null    int8
 5   mainroad          545 non-null    category
 6   guestroom         545 non-null    category
 7   basement          545 non-null    category
 8   hotwaterheating   545 non-null    category
 9   airconditioning   545 non-null    category
 10  parking           545 non-null    int8
 11  prefarea          545 non-null    category
 12  furnishingstatus  545 non-null    category
dtypes: category(7), int16(1), int32(1), int8(4)
memory usage: 10.0 KB

In [ ]:
#dtypes: int64(6), object(7), memory usage: 55.5+ KB
#dtypes: category(7), int16(1), int32(1), int8(4), memory usage: 10.0 KB
# памяти требуется 10кБ вместо 55,5кБ, что примерно в 5,5 раз меньше